# Generated by Django 6.0.2 on 2026-02-18 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=100)),
                ('domaine', models.CharField(max_length=200)),
                ('legal_info', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('emploi', 'Emploi'), ('stage', 'Stage')], max_length=20)),
                ('categorie', models.CharField(choices=[('academique', 'Stage académique'), ('professionnel', 'Stage professionnel'), ('poste', 'Poste de travail')], max_length=20)),
                ('profil_recherche', models.TextField()),
                ('attentes', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('statut', models.CharField(default='disponible', max_length=20)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offres.entreprise')),
            ],
        ),
    ]
