# Generated by Django 6.0.2 on 2026-02-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='legal_info',
            field=models.ImageField(blank=True, null=True, upload_to='logos_entreprises/'),
        ),
    ]
